signal_average_spk_noncanc = acc_stopping_extractSDF_noncanceled...
    (dirs,dataFiles_beh,dataFiles_neural,behavior);

signal_collapse_noncanc = neural_collapseSignalSession(signal_average_spk_noncanc,...
    'events',{'saccade'},...
    'conditions',{'NC','GO'},...
    'conditions_map',[1 2]);
acc_stopping_errorClustering

signal_average_spk_canc = acc_stopping_extractSDF_canceled(dirs,dataFiles_beh,dataFiles_neural,behavior);

signal_collapse_canc = neural_collapseSignalSession(signal_average_spk_canc,...
    'events',{'target','stopSignal_artifical','ssrt'},...
    'conditions',{'C','GO'},...
    'conditions_map',[1 2]);

acc_stopping_ssrtClustering

signal_collapse_canc = neural_collapseSignalSession(signal_average_spk_canc,...
    'events',{'target','stopSignal_artifical','ssrt'},...
    'conditions',{'C','GO'},...
    'conditions_map',[1 2]);